title: EoWW
description: End-of-work-week interesting links for interested people
baseurl: "/EoWW" 
url: "https://746a.github.io"
theme: minima

plugins:
  - jekyll-feed

collections:
  weeks:
    output: true
    permalink: /weeks/:name/
