title: EoW
description: End-of-week calm inspiration
baseurl: "" 
url: "https://746a.github.io/EoW"
theme: minima

plugins:
  - jekyll-feed

collections:
  weeks:
    output: true
    permalink: /weeks/:name/
